// Brand marks for the brand chips — monochrome SVGs from Simple Icons (CC0),
// kept in public/images/brands/<slug>.svg and painted in the chip's text
// colour through a CSS mask. A brand without a file simply shows as text.
// slug, or [slug, width in px] for marks that are wider than tall
const LOGOS: Record<string, string | [string, number]> = {
  audi: "audi",
  bmw: "bmw",
  chevrolet: "chevrolet",
  citroen: "citroen",
  dacia: "dacia",
  fiat: "fiat",
  ford: "ford",
  honda: "honda",
  hyundai: "hyundai",
  jeep: "jeep",
  kia: "kia",
  "land rover": ["landrover", 34],
  lexus: ["lexus", 24],
  mazda: "mazda",
  mercedes: "mercedes",
  "mercedes-benz": "mercedes",
  mitsubishi: "mitsubishi",
  nissan: "nissan",
  opel: "opel",
  peugeot: "peugeot",
  porsche: "porsche",
  ram: "ram",
  renault: "renault",
  skoda: "skoda",
  tesla: "tesla",
  toyota: "toyota",
  volkswagen: "volkswagen",
  vw: "volkswagen",
  volvo: "volvo",
  seat: "seat",
  cupra: "cupra",
  "alfa romeo": "alfaromeo",
  suzuki: "suzuki",
  subaru: "subaru",
  mini: "mini",
  smart: "smart",
  jaguar: "jaguar",
  infiniti: "infiniti",
  chrysler: "chrysler",
  cadillac: "cadillac",
  lincoln: "lincoln",
  gmc: "gmc",
  buick: "buick",
  acura: "acura",
  genesis: "genesis",
  maserati: "maserati",
  ferrari: "ferrari",
  lamborghini: "lamborghini",
  bentley: "bentley",
  "rolls-royce": "rollsroyce",
  "aston martin": "astonmartin",
  mg: "mg",
  byd: "byd",
  geely: "geely",
  chery: "chery",
  "great wall": "greatwall",
  haval: "haval",
  lada: "lada",
  uaz: "uaz",
  gaz: "gaz",
  isuzu: "isuzu",
  iveco: "iveco",
  man: "man",
  scania: "scania",
  daf: "daf",
};

/** the mark for a brand we have one for — url + box width — else null */
export function brandLogo(brand: string): { url: string; width: number } | null {
  const entry = LOGOS[brand.trim().toLowerCase()];
  if (!entry) return null;
  const [slug, width] = Array.isArray(entry) ? entry : [entry, 18];
  return { url: `/images/brands/${slug}.svg`, width };
}
